// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2VKc0_we0XP6Ghb5TGqrAZXobJdcauYk',
    appId: '1:546719296112:web:fa14c88040588bfc93a2b5',
    messagingSenderId: '546719296112',
    projectId: 'fir-second-2',
    authDomain: 'fir-second-2.firebaseapp.com',
    databaseURL: 'https://fir-second-2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-second-2.appspot.com',
    measurementId: 'G-85041NEFLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6rZlXKlXycie496-uAEeihLwouA7lUVE',
    appId: '1:546719296112:android:86cd5eaada77720d93a2b5',
    messagingSenderId: '546719296112',
    projectId: 'fir-second-2',
    databaseURL: 'https://fir-second-2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-second-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU4se7ufm3Wc5A1K2MNq6IPr3GoIA-ozs',
    appId: '1:546719296112:ios:27c5136b521f358893a2b5',
    messagingSenderId: '546719296112',
    projectId: 'fir-second-2',
    databaseURL: 'https://fir-second-2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-second-2.appspot.com',
    iosBundleId: 'com.example.firebaseWithBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU4se7ufm3Wc5A1K2MNq6IPr3GoIA-ozs',
    appId: '1:546719296112:ios:4b98bb322cd1fb8493a2b5',
    messagingSenderId: '546719296112',
    projectId: 'fir-second-2',
    databaseURL: 'https://fir-second-2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-second-2.appspot.com',
    iosBundleId: 'com.example.firebaseWithBloc.RunnerTests',
  );
}
